Update database.csv
france-connect/identity-provider-example pull request #112
Opened 2020-10-15 09:28 UTC by smedlej

Nous avons besoin d'un JDD avec un code postal de lieu de naissance ( code depart) < 10
Merci

2020-10-15 10:58 UTC, smedlej commented
Bonjour,
je précise qu'il s'agit d'un JDD pour le compte de la banque de France. ce JDD nous est utile afin de tester le cas où le code de département de naissance est inféreur à 10

2020-10-19 07:44 UTC, benratti requested changes
Pouvez vous plutôt ajouter une ligne plutot que de modifier une ligne existente qui potentiellement est utilisé par d'autres ?

2020-10-19 08:13 UTC, smedlej commented
Bonjour,
le JDD modifié est un JDD créé au paravant spécifiquement pour le compte de la Banque de france afin de tester la fusion entre un compte certifié "FC" et un compte non certifié (Bdf).
souhaitez-vous quand même qu'on ajoute une autre ligne?

2020-10-24 09:04 UTC, closed without merging

2020-10-24 09:04 UTC, benratti commented
Fait dans une autre pull request