Add "a_18_ans" use case
france-connect/identity-provider-example pull request #129
Opened 2021-01-28 09:56 UTC by virgile-dev

Added line 132

Nous essayons de limiter au maximum l'ajout d'identités dans le fichier [database.csv](database.csv) pour réduire les coûts de maintenance et limiter les risques de non conformité au RGPD.

Si vous avez modifié ce fichier, pouvez vous nous préciser ce qui vous a manqué dans les identités déjà présentes dans le fichier et en quoi vos identités résolvent le problème ?

2021-02-17 17:03 UTC, benratti commented
Bonjour, 

Pouvez vous préciser le contexte de votre demande ?

2021-03-12 16:07 UTC, virgile-dev commented
Bonjour, 
Nous travaillons avec l'Assemblée Nationale sur le site petitions.assemblee-nationale.fr
Nous avons récemment un souci avec des utilisateurs ayant 18 ans. 
Je me suis rendu compte en faisant la recette je n'avais pas de compte test qui permettait de tester ce scénario là.

Cordialement,

2021-03-17 09:20 UTC, benratti requested changes
Le format de la date de naissance n'est pas correct. 
Merci de le mettre au format YYYY-MM-JJ

2021-03-17 11:41 UTC, virgile-dev commented
@benratti désolé pour l'erreur. C'est corrigé :)

2022-06-28 09:00 UTC, closed without merging