Update database.csv
france-connect/identity-provider-example pull request #161
Opened 2021-07-30 12:05 UTC by SylMolina

Dans le cadre du projet Maprocuration (Ministère Intérieur) nous avons besoin de créer un utilisateur qui existe dans le REU

Nous essayons de limiter au maximum l'ajout d'identités dans le fichier [database.csv](database.csv) pour réduire les coûts de maintenance et limiter les risques de non conformité au RGPD.

Si vous avez modifié ce fichier, pouvez vous nous préciser ce qui vous a manqué dans les identités déjà présentes dans le fichier et en quoi vos identités résolvent le problème ?

Il me manque une identité avec les mêmes nom, prénom et date de naissance que celles figurants dans le REU. La modification dans le REU n'est pas possible. Si une des identités existantes FC peut être modifiées avec les 3 valeurs indiquées pour les nom prenom et date de naissance cela fonctionnera également.

2021-07-30 13:42 UTC, SylMolina commented
Il me manque une identité avec les mêmes nom, prénom et date de naissance que celles figurants dans le REU. La modification dans le REU n'est pas possible. Si une des identités existantes FC peut être modifiées avec les 3 valeurs indiquées pour les nom prenom et date de naissance cela fonctionnera également.

2021-08-03 07:45 UTC, SylMolina commented
Bonjour, 

Avez vous du nouveau sur ce sujet qui est bloquant pour nos tests ?
Par avance merci

2021-08-09 16:08 UTC, Melanieroge requested changes
Bonjour,
Pour des raisons de sécurité, nous ne pouvons pas permettre de création de comptes avec des identités réelles. Vous devez utiliser des données fictives dans le cadre des tests et de la recette. 
Nous ne pouvons donc accepter cette demande d'ajout.

2021-08-09 16:20 UTC, SylMolina commented
Pouvez vous préciser car toutes les données individuelles en béta dans le REU sont des données fictives.
ABDELJALIL Cédric Jean n'existe pas.

2021-08-09 16:40 UTC, Melanieroge commented
Bonjour, 
Après discussion avec mes collègues nous acceptons votre demande. 
Bien cordialement,

2021-08-09 16:41 UTC, Melanieroge approved these changes

2021-08-09 16:43 UTC, merged