Create JDD_FC_MSA.csv
france-connect/identity-provider-example pull request #162
Opened 2021-08-03 15:25 UTC by greg-iMSA

Nous essayons de limiter au maximum l'ajout d'identités dans le fichier [database.csv](database.csv) pour réduire les coûts de maintenance et limiter les risques de non conformité au RGPD.

Si vous avez modifié ce fichier, pouvez vous nous préciser ce qui vous a manqué dans les identités déjà présentes dans le fichier et en quoi vos identités résolvent le problème ?

2021-08-05 15:05 UTC, Melanieroge requested changes
Bonjour, 
Merci de changer les intitulés des colonnes afin que ceux-ci correspondent à nos intitulés (même nom et même ordre de colonne) 
EX: 
id | identifiant | motDePasse | nomDeNaissance | nomDUsage | prenoms | genre | email | telephone | dateDeNaissance | codePostalLieuDeNaissance | codePaysDeNaissance | adressePays | adresseVille | adresseCodePostal | adresseVoie | 

Merci

2021-08-05 15:32 UTC, greg-iMSA commented
Bonjour, j'ai changé la première ligne du fichier pour mettre les mêmes noms de colonnes.

2021-08-06 14:00 UTC, Melanieroge commented
Bonjour, 

Nous vous prions de bien vouloir nous excuser pour ce nouveau retour. Nous n'avions pas remarqué précédemment que votre tableau ne comprend aucune adresse email. Celle-ci étant une donnée obligatoire pour que la cinématique s'effectue, merci de renseigner des adresses emails fictives (ex: yopmail) pour l'ensemble des identités tests.

2021-08-06 14:59 UTC, Melanieroge approved these changes

2021-08-06 15:00 UTC, greg-iMSA commented
Bonjour,

J'ai rajouté les adresses mail. Etant donné que nous n'utilisons pas cette donnée, j'ignorais qu'elle était obligatoire...

2021-08-06 15:00 UTC, merged