Create JDD-MES-FC.csv
france-connect/identity-provider-example pull request #231
Opened 2023-02-22 16:52 UTC by Kristoff1981

création d'un JDD avec carte vitale associée

Nous essayons de limiter au maximum l'ajout d'identités dans le fichier [database.csv](database.csv) pour réduire les coûts de maintenance et limiter les risques de non conformité au RGPD.

Si vous avez modifié ce fichier, pouvez vous nous préciser ce qui vous a manqué dans les identités déjà présentes dans le fichier et en quoi vos identités résolvent le problème ?
les identitées déjà présentes n'étaient pas présentes dans nos bases avec NIR et carte vitale associées

2023-02-22 17:17 UTC, Melanieroge requested changes
Bonjour, 
Ce tableau semble contenir certaines données liées à des identités réelles (nom de naissance, nom d'usage et prénom ex : Boivin Solaine). 
Pour des raisons de sécurité, nous ne pouvons malheureusement pas permettre la création de ces comptes car des données fictives doivent être utilisées dans le cadre de la recette.
Pourriez-vous modifier ces données? 
Dans l'attente de votre retour, 
Merci beaucoup

2023-02-23 06:59 UTC, Kristoff1981 reviewed
suppression des 3 id non issues de données fictives

2023-02-23 09:19 UTC, benratti requested changes
Il faut supprimer la première ligne qui contient la description du fichier.

2023-02-23 09:35 UTC, Kristoff1981 reviewed
suppression de 1ère ligne qui contenait l'entête

2023-02-23 09:50 UTC, LeilaAbdesslam approved these changes

2023-02-23 10:02 UTC, sherman-dinum approved these changes

2023-02-23 10:05 UTC, benratti approved these changes

2023-02-23 10:06 UTC, merged